### ISSUE TITLE
Information Centre: content does not show up ,in the list (in editor), unable to edit

### ISSUE THREAD

**Issue by AnneliesVerroken** [micado-eu/pa_application#97] opened 2020-12-09 12:55 UTC
I tried to make 2 new fact sheets in the information centre, i entered the content, but after saving, the title is not shown in the list of items and I am unable to edit (edit page loads forever). 

 Nothing of this is shown in the migrant app.

![Information center  non published description](https://user-images.githubusercontent.com/75615204/101632456-39ee0300-3a26-11eb-99bc-8870079402f6.PNG)

**Comment by ivchicano** [comment] 2020-12-09 13:21
Hello, sorry for the inconvenience and thanks for the feedback.
Taking a look into it looks like the english language didn't get saved. Can I ask what did you tried to add in the title and the description of the fact sheets?

**Comment by AnneliesVerroken** [comment] 2020-12-09 13:36
I think I wanted to try call the fact sheet "Validate your diploma". The description was a mixture of text, a link and I added some bullets but those didnt want to stay in place ;) after I saved, I couldnt get back in and I saw neither title nor descrition showed up in the list.

**Comment by ivchicano** [comment] 2020-12-16 09:11
I can't seem to reproduce the issue, do you still have this problem when adding new elements?

**Comment by AnneliesVerroken** [comment] 2020-12-16 10:01
Good morning,

I can add a fact sheet in the information center, I can edit and it shows in the migrant app

Have a great day!

Annelies

Van: Iván Chicano [mailto:notifications@github.com]
Verzonden: woensdag 16 december 2020 10:12
Aan: micado-eu/pa_application
CC: Annelies Verroken; Author
Onderwerp: Re: [micado-eu/pa_application] Information Centre: content does not show up ,in the list (in editor), unable to edit (#97)


I can't seem to reproduce the issue, do you still have this problem when adding new elements?

**Comment by ivchicano** [comment] 2020-12-16 10:02
Thanks for the help, closing this issue

**Closed by ivchicano** 2020-12-16 10:02 UTC
Labels: bug
