### ISSUE TITLE
Are links in-app possible?

### ISSUE THREAD

**Issue by AnneliesVerroken** [micado-eu/pa_application#109] opened 2020-12-21 13:35 UTC
Is it possible to make internal links? I might just not know how, but right now I miss the possibility to make link to information within the application. For example from an event to a guided process or from the information center to the events.

**Comment by gioppoluca** [comment] 2021-01-04 08:59
This is a duplicate of #76 and we stated that at the moment is not a feature in the current release.

**Closed by gioppoluca** 2021-01-04 08:59 UTC
Labels: duplicate, enhancement
